# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DNDAssistant' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DNDAssistant

  #pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  #pod 'React', :path => '../node_modules/react-native', :subspecs => [
  #  'Core',
  #  'RCTActionSheet',
  #  'RCTAnimation',
  #  'RCTGeolocation',
  #  'RCTImage',
  #  'RCTLinkingIOS',
  #  'RCTNetwork',
  #  'RCTSettings',
  #  'RCTText',
  #  'RCTVibration',
  #  'RCTWebSocket'
  #]

  #pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'Google/SignIn'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'DNDAssistantTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
